In [16]:
import torch

### Now I understand the thing below that is and equation and the X is equal to 2 that is the value of the tensor x

In [17]:
x = torch.tensor(2.0, requires_grad=True) # this acativate the computational graphic

In [18]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
y

tensor(63., grad_fn=<AddBackward0>)

In [19]:
y.backward()

In [20]:
x.grad # this represent if you plug the first value of x in the derivative of y

tensor(93.)

## Multidimensional backpropagation

In [21]:
x = torch.tensor([[1., 2., 3.], [3., 2., 1.]], requires_grad=True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [22]:
y = 3*x + 2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [23]:
z = 2*y**2 # x one uses the y values and y uses x values so they are dependent each other
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [24]:
out = z.mean()
out

tensor(140., grad_fn=<MeanBackward0>)

### Do the back propagation

In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
