In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

np_array = np.array(mylist)


In [4]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

matrix = np.array(mylist)
matrix.shape

(3, 3)

# Creating arrays

In [5]:
# arange
np.arange(0 , 1)
np.arange(0 , 1, 0.5) # the third parameter is the step how it increase this value


array([0. , 0.5])

In [6]:
# with numpy you can do things like this
np.ones((5, 5)) * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [7]:
# but with python
[1, 2, 3] * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
#used to give the start and the end and then how many numbers do you want between them
np.linspace(0, 10, 2)

array([ 0., 10.])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.random.rand(1)

array([0.30219631])

In [11]:
# it uses to give a number of normal distribution so from 0 with a standart deviation of 1
np.random.randn(10)

array([ 0.34339363, -1.01592122,  0.65156782, -0.05869302,  0.42333313,
        0.16133979, -0.04536948,  1.77696589,  0.80881723,  1.44575774])

In [12]:
# int random number from the first one to the last one but not including the second parameter
np.random.randint(0, 2)

0

In [13]:
# we use the seed to replicate the values obtained but it must be in the same cell
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [14]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [15]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
#getting the min and max
print(ranarr.min())
print(ranarr.max())

# for getting the index of thats
print(ranarr.argmax())
print(ranarr.argmin())

10
48
1
6


In [17]:
# type of data
ranarr.dtype

dtype('int32')

# Index selection

In [18]:
arr = np.arange(0, 11)
arr[8]

8

In [19]:
arr[3:7]

array([3, 4, 5, 6])

In [20]:
arr = arr + 100
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [21]:
# is alredy pointing to the original array
slice = arr[0:6]
slice[:] = 99
print(slice)
print(arr)

# for don't do that you can do this
copy = arr.copy()
copy[0:6] = 99
print(copy)

[99 99 99 99 99 99]
[ 99  99  99  99  99  99 106 107 108 109 110]
[ 99  99  99  99  99  99 106 107 108 109 110]


In [22]:
# Indexing on a matrix
arr2d = np.arange(5, 50, 5).reshape((3, 3))
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# Using indexes
arr2d[2, 2]

45

In [24]:
# multiply selection
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
# Conditional selection
cdarr = np.arange(1, 11)
bool_arr = cdarr > 4
print(bool_arr)
cdarr[bool_arr]

[False False False False  True  True  True  True  True  True]


array([ 5,  6,  7,  8,  9, 10])

In [26]:
cdarr[cdarr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Operations with arrays

In [27]:
arr = np.arange(0, 11)

In [28]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
1/arr

D:\Users\iperez\anaconda3\envs\pytorchcourseenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [30]:
arr.sum()

55

In [31]:
arr_2d = np.arange(1, 13).reshape((3, 4))

#sum all the columns or rows
arr_2d.sum(axis=0) # is the sum across the rows

arr_2d.sum(axis=1) # is the sum across the columns

array([10, 26, 42])