In [2]:
import numpy as np
import torch

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [5]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [7]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [8]:
arr[0] = 100 # create a link between them
x

tensor([100,   2,   3,   4,   5], dtype=torch.int32)

In [9]:
my_arr = np.arange(0, 10)
my_tensor = torch.Tensor(my_arr) # don't create a link between the array and just make a copy
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Part two

In [10]:
new_arr = np.array([1,2,3])

print(torch.Tensor(new_arr)) # is float tensor
print(torch.tensor(new_arr)) # inherit the type


tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [23]:
# initialize tensors
tensor = torch.empty(2,2)

In [14]:
torch.zeros(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones(3, 1)

tensor([[1.],
        [1.],
        [1.]])

In [21]:
torch.arange(0, 20, 2).reshape(2, 5)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [24]:
# change the type
tensor.type(torch.int32)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [25]:
# create with random numbers
torch.rand(4, 3) # normal distribution between 0 and 1

tensor([[0.7405, 0.5314, 0.2159],
        [0.1918, 0.0388, 0.7723],
        [0.5443, 0.3588, 0.9640],
        [0.8346, 0.3518, 0.8694]])

In [26]:
torch.randn(4, 3) # std = 1

tensor([[-0.0979,  0.0315, -0.3940],
        [ 0.9466,  1.4163,  0.8730],
        [-0.4554,  1.5405,  0.9045],
        [ 2.5526,  1.3048, -0.2394]])

In [31]:
torch.randint(low=0, high=11, size=(2, 2)) # betweem number with a size

tensor([[6, 1],
        [4, 4]])

In [36]:
x = torch.zeros(2, 5)

In [37]:
# generate a random tensor from other tensor size
torch.rand_like(x)

tensor([[0.0819, 0.6987, 0.9442, 0.1848, 0.4381],
        [0.4560, 0.7957, 0.6272, 0.2286, 0.8613]])

In [42]:
torch.randn_like(x)

tensor([[ 2.4688,  0.0326, -0.4208, -0.6731, -0.7860],
        [ 1.2004, -1.5488,  0.4839,  0.6522,  1.4736]])

In [41]:
torch.randint_like(x, low=0, high=11)

tensor([[9., 7., 8., 6., 7.],
        [2., 2., 5., 1., 9.]])

In [43]:
# seed
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])