In [1]:
import numpy as np
import torch

In [4]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
x[1,1]

<function Tensor.values>

In [8]:
x[:, 1]

tensor([1, 3, 5])

In [9]:
# if you want to conserve the columns
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [11]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x.reshape(2, 5) # don't save

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = x.reshape(2, 5)

In [17]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
z = x.view(2, 5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x[0] = 999
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [22]:
z # it creaates like a link

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [23]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Infer what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### Operations

In [28]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])

In [29]:
a + b

tensor([5., 7., 9.])

In [30]:
torch.add(a, b)

tensor([5., 7., 9.])

In [34]:
# to add to the actual value
a.mul_(b)

tensor([ 4., 10., 18.])

In [35]:
a

tensor([ 4., 10., 18.])

## Part two

In [36]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])

In [37]:
# dot product
a.dot(b)

tensor(32.)

In [42]:
# 2d matrix multiplication (it have to match the number of columns of the 1st with the number of rows of the 2nd)
a = torch.tensor([[0, 2, 4], [1, 3, 5]])
b = torch.tensor([[6,7], [8, 9], [10, 11]])
print(a, b)


tensor([[0, 2, 4],
        [1, 3, 5]]) tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])


In [43]:
torch.mm(a, b) # the same than
a @ b

tensor([[56, 62],
        [80, 89]])