In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']

In [4]:
mylist = [10, 20, 30]

In [5]:
arr = np.array(mylist)
arr

array([10, 20, 30])

In [6]:
d = {'a':10, 'b':20, 'c':30}

In [7]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data=arr, index=labels) # not must be the same type

a    10
b    20
c    30
dtype: int32

In [9]:
ser1 = pd.Series([1, 2, 3, 4], index=['USA', 'Germany', 'USSR', 'JAPAN'])

In [10]:
ser2 = pd.Series([1, 3, 4, 5],  index=['USA', 'Germany', 'Italy', 'JAPAN'])

In [11]:
ser1 + ser2

Germany    5.0
Italy      NaN
JAPAN      9.0
USA        2.0
USSR       NaN
dtype: float64

## DATAFRAMES

In [12]:
from numpy.random import randn

np.random.seed(101)

rand_mat = randn(5, 4)

In [13]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [14]:
df = pd.DataFrame(data=rand_mat, index='A B C D E'.split(), columns='W X Y Z'.split())

In [15]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
df[['W', 'Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [17]:
df['NEW'] = df['W'] + df['Y']

In [18]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [19]:
# key error passing wrong index or axis or name
df.drop('NEW', axis=1, inplace=True) # put inplace into True to delete directly

In [20]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Rows

In [21]:
df.drop('A')

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [23]:
df.loc[['A', 'B'], ['Y', 'Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965

In [24]:
df.iloc[0:4]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

## Comparison

In [25]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [26]:
df[df > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df[df['W'] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
cond1 = df['W'] > 0
cond2 = df['Y'] > 1

In [29]:
df[ (cond1) & (cond2)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [31]:
new_ind = 'CA NY WY OR CO'.split()

In [32]:
df['States'] = new_ind
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [33]:
# set new index
df.set_index('States', inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
W    5 non-null float64
X    5 non-null float64
Y    5 non-null float64
Z    5 non-null float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [35]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [36]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [37]:
# get the count of the different true values
ser_w = df['W'] > 0
sum(ser_w)

4

## GroupBy

In [38]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [39]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [40]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## Operations

In [41]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [42]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [43]:
df['col2'].nunique()

3

In [44]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [45]:
# Col1 > 2
# Col2 == 444
newdf = df[(df['col1'] > 2) & (df['col2']==444)]
newdf

col1  col2 col3
3     4   444  xyz

In [46]:
def times_two(num):
    return num*2

times_two(2)

4

In [47]:
df['new'] = df['col1'].apply(times_two)
df


col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [48]:
del df['new']

In [49]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [50]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [51]:
# sort
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

## INPUT OUTPUT


In [52]:
df = pd.read_csv('example.csv') # introduce the full path if it doesn't is in the same folde


In [53]:
newdf = df[['a', 'b']]

In [54]:
newdf.to_csv('mynew.csv')


## Tests

In [72]:
dt = pd.read_csv('bank.csv')

